kind: ResourceQuota
apiVersion: v1
metadata:
  name: not-best-effort
spec:
  hard:
    limits.cpu: '16'
    limits.memory: 20Gi
    requests.cpu: '4'
    requests.memory: 16Gi
  scopes:
    - NotTerminating
    - NotBestEffort