apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gitea-admin-secret.yaml

helmGlobals:
  chartHome: ./charts

helmCharts:
- name: forgejo
  releaseName: test-forgejo
  valuesFile: values.yaml


generatorOptions:
  disableNameSuffixHash: true


