apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- forgejo-admin-secret.yaml

## If you have no registry for helm charts use the second method defined in the Readme and this definition:
# helmGlobals:
#   chartHome: ./charts

helmCharts:
- name: forgejo
  # in the disconnected use case overwrite this URL with your helm repo container
  repo: oci://code.forgejo.org/forgejo-helm/
  version: 11.0.1
  releaseName: pp-forgejo-test
  valuesFile: values.yaml
  additionalValuesFiles:
  # use this for single instances
  # - values-postgresql.yaml
  # - values-redis.yaml
  # use this for a redundant installation (production)
  - values-postgresql-ha.yaml
  - values-redis-ha.yaml

generatorOptions:
  disableNameSuffixHash: true
#

