postgresql:
  enabled: true
  # if you want another version of postgres
  # image:
  #   tag: 17.2.0-debian-12-r6
  resources:
    limits:
      cpu: 300m
      memory: 250Mi
    requests:
      cpu: 150m
      memory: 125Mi

postgresql-ha:
  enabled: false
#