postgresql:
  enabled: false

postgresql-ha:
  enabled: true
  image:
    tag: 17.2.0-debian-12-r7
  resources:
    limits:
      cpu: 300m
      memory: 250Mi
    requests:
      cpu: 150m
      memory: 125Mi
