redis-cluster:
  enabled: true
  image:
    tag: 7.4.2-debian-12-r0
  resources:
    limits:
      cpu: 300m
      memory: 128Mi
    requests:
      cpu: 150m
      memory: 64Mi

redis:
  enabled: false

