# here comes your forgejo instance domain name
_domain: &domain pp-forgejo-test.develop.pflaeging.net
# the complete URL for your instance
_rootUrl: &rootUrl https://pp-forgejo-test.develop.pflaeging.net/
# the name of the forgejo-admin-secret: This is typically
#   PREFIX-forgejo-admin-secret-SUFFIX
_adminSecretName: &adminSecretName pp-forgejo-admin-secret-test
# the name of the postgres-app-secret: This is typically
#   PREFIX-forgejo-postgres-SUFFIX-app
_postgresSecretName: &postgresSecretName pp-forgejo-postgres-test-app

global:
  compatibility:
    openshift:
      adaptSecurityContext: force
  # define your block storage class    
  defaultStorageClass: rook-cephfs

replicaCount: 1

route:
  enabled: true
  # enable cert-manager controlled tls
  annotations:
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: letsencrypt-prod
  host: *domain

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

initContainers:
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

persistence:
  enabled: true
  # use shared storage for your repos
  storageClass: rook-cephfs
  # define the size of your storage
  size: 10Gi
  claimName: forgejo-shared-storage
  accessModes: 
  - ReadWriteMany

gitea:
  APP_NAME: 'pflaeging.net git Repository'
  admin:
    # this secret must have the same name as the one in your kustomization.yaml
    existingSecret: *adminSecretName
  config:
    server:
      DOMAIN: *domain
      ROOT_URL: *rootUrl
##########
## Customize part begins here
      ## you can disable ssh server if you don't want to use this protocol
      # DISABLE_SSH: true
      # we use http as protocol, because we're behind an ingress (TLS termination on ingress)
      PROTOCOL: http
      # internal git user
      BUILTIN_SSH_SERVER_USER: gituser
      # external ssh port if you expose it via NodePort service
      SSH_PORT: 32225
    actions:
      # actions are disabled (no runner in kubernetes for the moment)
      ENABLED: false
    service:
      # decide if you want self registration
      DISABLE_REGISTRATION: true
##########
## End customize part
  additionalConfigFromEnvs:
    - name: FORGEJO__DATABASE__PASSWD
      valueFrom:
        secretKeyRef:
          name: *postgresSecretName
          key: password
    - name: FORGEJO__DATABASE__HOST
      valueFrom:
        secretKeyRef:
          name: *postgresSecretName
          key: host
    - name: FORGEJO__DATABASE__NAME
      valueFrom:
        secretKeyRef:
          name: *postgresSecretName
          key: dbname
    - name: FORGEJO__DATABASE__USER
      valueFrom:
        secretKeyRef:
          name: *postgresSecretName
          key: user

## Optional: listen ssh on NodePort (maybe you have to enable this by your k8s team)
service:
  ssh:
    type: NodePort
    port: 22
    nodePort: 32225
