apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: forgejo

resources:
- ../templates/forgejo-okd/base

secretGenerator:
  - name: forgejo-admin-secret
    envs:
    - forgejo-admin-secret.env

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
- name: forgejo
  repo: oci://code.forgejo.org/forgejo-helm/
  version: 14.0.3
  releaseName: forgejo
  valuesFile: ../templates/forgejo-okd/base/forgejo/values.yaml
  additionalValuesFiles:
  - forgejo-config.yaml

patches:
- target:
    kind: Cluster
    name: forgejo-postgres
  path: postgres-config.yaml
- target:
    kind: StatefulSet
    name: valkey
  path: valkey-config.yaml